//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class giedaEntities : DbContext
    {
        public giedaEntities()
            : base("name=giedaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<allotee_plots> allotee_plots { get; set; }
        public virtual DbSet<allottee_documents> allottee_documents { get; set; }
        public virtual DbSet<allottee_payments> allottee_payments { get; set; }
        public virtual DbSet<allottee> allottees { get; set; }
        public virtual DbSet<data_update> data_update { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<installment_payments> installment_payments { get; set; }
        public virtual DbSet<installment> installments { get; set; }
        public virtual DbSet<other_charges> other_charges { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<phase> phases { get; set; }
        public virtual DbSet<plot> plots { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<surcharge> surcharges { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Userss> Usersses { get; set; }
        public virtual DbSet<UserLoginTimeLog> UserLoginTimeLogs { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
