//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class installment_payments
    {
        public int id { get; set; }
        public int allottee_id { get; set; }
        public int installment_id { get; set; }
        public string title { get; set; }
        public int due_amount { get; set; }
        public System.DateTime due_date { get; set; }
        public int amount { get; set; }
        public int surcharge { get; set; }
        public System.DateTime paid_on { get; set; }
        public int total_amount { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual allottee allottee { get; set; }
    }
}
