//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class plot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plot()
        {
            this.allotee_plots = new HashSet<allotee_plots>();
            this.installments1 = new HashSet<installment>();
            this.other_charges = new HashSet<other_charges>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string size { get; set; }
        public string description { get; set; }
        public Nullable<int> down_payment { get; set; }
        public string form_fee { get; set; }
        public string total_price { get; set; }
        public string installments { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> phase_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<allotee_plots> allotee_plots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<installment> installments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<other_charges> other_charges { get; set; }
        public virtual phase phase { get; set; }
    }
}
