//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class surcharge
    {
        public int id { get; set; }
        public string title { get; set; }
        public int amount { get; set; }
        public System.DateTime paid_on { get; set; }
        public int due_amount { get; set; }
        public System.DateTime due_date { get; set; }
    }
}
